# Generated by Django 3.0.3 on 2020-04-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
